language: node_js
sudo: true
node_js:
  - "node"
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
  - npm install https://github.com/GoogleChrome/puppeteer
script:
  - npm test -- --coverage
after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  
