window.onload = function addOrderItems(){
    items = JSON.parse(localStorage.getItem('orderItems'))
    total = 0.00
    items.forEach((item) => {
        let tr = document.createElement('tr')
        let imageTd = document.createElement('td')
        let image = document.createElement('img')
        image.setAttribute("src", item.image)
        imageTd.appendChild(image)
        let nameTd = document.createElement('td')
        let nameText = document.createTextNode(item.name)
        nameTd.appendChild(nameText)
        let priceTd = document.createElement('td')
        let priceText = document.createTextNode(item.price)
        priceTd.appendChild(priceText)
        let quantityTd = document.createElement('td')
        let input = document.createElement('input')
        input.setAttribute('type', 'number')
        input.setAttribute('name', 'quantity')
        input.setAttribute('value', item.quantity)
        input.setAttribute('id', 'quantity')
        quantityTd.appendChild(input)
        let subtotalTd = document.createElement('td')
        let subtotalText = document.createTextNode(item.price * item.quantity)
        total += item.price * item.quantity
        subtotalTd.appendChild(subtotalText)
        let buttonTd = document.createElement('td')
        let button = document.createElement('button')
        button.setAttribute("id", "remove")
        let buttonText = document.createTextNode('Remove')
        button.appendChild(buttonText)
        button
        buttonTd.appendChild(button)
        tr.appendChild(imageTd)
        tr.appendChild(nameTd)
        tr.appendChild(priceTd)
        tr.appendChild(quantityTd)
        tr.appendChild(subtotalTd)
        tr.appendChild(buttonTd)
        document.getElementById('orderItems').appendChild(tr)
    })
    let checkoutTr = document.createElement('tr')
    let totalTd = document.createElement('td')
    totalTd.setAttribute("colspan", "4")
    let strong = document.createElement('strong')
    let totalText = document.createTextNode('Total: KES '+ total)
    strong.appendChild(totalText)
    totalTd.appendChild(strong)
    let orderTd = document.createElement('td')
    orderTd.setAttribute('colspan', '2')
    let orderButton = document.createElement('button')
    orderButton.setAttribute('class', 'call_to')
    orderButton.setAttribute('id', 'checkout')
    let orderButtonText = document.createTextNode('Checkout')
    orderButton.appendChild(orderButtonText)
    orderButton.addEventListener('click', postOrder)
    orderTd.appendChild(orderButton)
    checkoutTr.appendChild(totalTd)
    checkoutTr.appendChild(orderTd)
    document.getElementById('orderItems').appendChild(checkoutTr)
}